Fix shellcheck warnings

diff --git a/scripts/pkg-tools/complete-filelist-dpkg b/scripts/pkg-tools/complete-filelist-dpkg
--- a/scripts/pkg-tools/complete-filelist-dpkg
+++ b/scripts/pkg-tools/complete-filelist-dpkg
@@ -1,4 +1,4 @@
-#/bin/sh
+#!/bin/sh
 #
 # Create a complete file list for all installed packages
 # dpkg version
@@ -7,7 +7,7 @@
 # License: GPL V2
 
 
-SCRIPT_NAME=$(basename $0)
+SCRIPT_NAME=$(basename "$0")
 
 die()
 {
@@ -19,8 +19,8 @@ die()
 
 create_tmpdir()
 {
-    test -d $TMPDIR || mkdir -p -m 700 $TMPDIR
-    test -d $TMPDIR || die "Can't create tmp dir $TMPDIR"
+    test -d "$TMPDIR" || mkdir -p -m 700 "$TMPDIR"
+    test -d "$TMPDIR" || die "Can't create tmp dir $TMPDIR"
 }
 
 
@@ -29,10 +29,9 @@ create_tmpdir()
 
 check_tmpdir_security()
 {
-
-    test $(stat $TMPDIR --format "%u") -eq $(id -u) || die "$TMPDIR: Wrong user ownership"
-    test $(stat $TMPDIR --format "%g") -eq $(id -g) || die "$TMPDIR: Wrong group ownership"
-    chmod 700 $TMPDIR
+    test "$(stat "$TMPDIR" --format "%u")" -eq "$(id -u)" || die "$TMPDIR: Wrong user ownership"
+    test "$(stat "$TMPDIR" --format "%g")" -eq "$(id -g)" || die "$TMPDIR: Wrong group ownership"
+    chmod 700 "$TMPDIR"
 }
 
 
@@ -48,8 +47,8 @@ FILELIST=$TMPDIR/filelist.txt
 
 create_pkglist()
 {
-    dpkg-query --show --showformat '${Package}:${Architecture}\n' >$PKGLIST
-    wc -l $PKGLIST
+    dpkg-query --show --showformat '${Package}:${Architecture}\n' >"$PKGLIST"
+    wc -l "$PKGLIST"
 }
 
 
@@ -61,11 +60,11 @@ clear_last_line()
 
 get_complete_filelist()
 {
-    rm -f $FILELIST_RAW
-    rm -f $FILELIST
+    rm -f "$FILELIST_RAW"
+    rm -f "$FILELIST"
 
     echo "Reading file lists..."
-    xargs <$PKGLIST dpkg --listfiles >>$FILELIST_RAW
+    xargs <"$PKGLIST" dpkg --listfiles >>"$FILELIST_RAW"
     clear_last_line
 }
 
@@ -74,17 +73,17 @@ filter_filelist()
 {
     echo "Filtering file list... "
 
-    sed -e 's/^diverted by.*to: //' <$FILELIST_RAW  | \
-    sed -e 's/^package diverts others to: //'	    | \
-    grep -v 'does not contain any files'	    | \
-    sort -u					    | \
-    grep -v '^ *$'				    | \
-    grep -v '^/\.$' >$FILELIST
+    sed -e 's/^diverted by.*to: //' <"$FILELIST_RAW"  | \
+    sed -e 's/^package diverts others to: //'         | \
+    grep -v 'does not contain any files'              | \
+    sort -u                                           | \
+    grep -v '^ *$'                                    | \
+    grep -v '^/\.$' >"$FILELIST"
 
     clear_last_line
-    wc -l $FILELIST
+    wc -l "$FILELIST"
 
-    rm $FILELIST_RAW
+    rm "$FILELIST_RAW"
 }
 
 
diff --git a/scripts/pkg-tools/complete-filelist-rpm b/scripts/pkg-tools/complete-filelist-rpm
--- a/scripts/pkg-tools/complete-filelist-rpm
+++ b/scripts/pkg-tools/complete-filelist-rpm
@@ -1,4 +1,4 @@
-#/bin/sh
+#!/bin/sh
 #
 # Create a complete file list for all installed packages
 # rpm version
@@ -7,7 +7,7 @@
 # License: GPL V2
 
 
-SCRIPT_NAME=$(basename $0)
+SCRIPT_NAME=$(basename "$0")
 
 TMPDIR=/tmp/qdirstat-$USER
 PKGLIST=$TMPDIR/pkglist.txt
@@ -24,8 +24,8 @@ die()
 
 create_tmpdir()
 {
-    test -d $TMPDIR || mkdir -p -m 700 $TMPDIR
-    test -d $TMPDIR || die "Can't create tmp dir $TMPDIR"
+    test -d "$TMPDIR" || mkdir -p -m 700 "$TMPDIR"
+    test -d "$TMPDIR" || die "Can't create tmp dir $TMPDIR"
 }
 
 
@@ -34,22 +34,21 @@ create_tmpdir()
 
 check_tmpdir_security()
 {
-
-    test $(stat $TMPDIR --format "%u") -eq $(id -u) || die "$TMPDIR: Wrong user ownership"
-    test $(stat $TMPDIR --format "%g") -eq $(id -g) || die "$TMPDIR: Wrong group ownership"
-    chmod 700 $TMPDIR
+    test "$(stat "$TMPDIR" --format "%u")" -eq "$(id -u)" || die "$TMPDIR: Wrong user ownership"
+    test "$(stat "$TMPDIR" --format "%g")" -eq "$(id -g)" || die "$TMPDIR: Wrong group ownership"
+    chmod 700 "$TMPDIR"
 }
 
 
 get_complete_filelist()
 {
-    rm -f $FILELIST
-    
+    rm -f "$FILELIST"
+
     echo -n "Reading file lists... "
-    rpm -qla | sort -u >$FILELIST
+    rpm -qla | sort -u >"$FILELIST"
     echo " done"
 
-    wc -l $FILELIST
+    wc -l "$FILELIST"
 }
 
 
diff --git a/scripts/pkg-tools/show-unpkg-files b/scripts/pkg-tools/show-unpkg-files
--- a/scripts/pkg-tools/show-unpkg-files
+++ b/scripts/pkg-tools/show-unpkg-files
@@ -6,8 +6,8 @@
 # License: GPL V2
 #
 
-SCRIPT_NAME=$(basename $0)
-SCRIPT_DIR=$(dirname $0)
+SCRIPT_NAME=$(basename "$0")
+SCRIPT_DIR=$(dirname "$0")
 
 TMPDIR=/tmp/qdirstat-$USER
 ROOT_CACHE=$TMPDIR/root.cache.gz
@@ -27,8 +27,8 @@ die()
 
 create_tmpdir()
 {
-    test -d $TMPDIR || mkdir -p -m 700 $TMPDIR
-    test -d $TMPDIR || die "Can't create tmp dir $TMPDIR"
+    test -d "$TMPDIR" || mkdir -p -m 700 "$TMPDIR"
+    test -d "$TMPDIR" || die "Can't create tmp dir $TMPDIR"
 }
 
 
@@ -37,10 +37,9 @@ create_tmpdir()
 
 check_tmpdir_security()
 {
-
-    test $(stat $TMPDIR --format "%u") -eq $(id -u) || die "$TMPDIR: Wrong user ownership"
-    test $(stat $TMPDIR --format "%g") -eq $(id -g) || die "$TMPDIR: Wrong group ownership"
-    chmod 700 $TMPDIR
+    test "$(stat "$TMPDIR" --format "%u")" -eq "$(id -u)" || die "$TMPDIR: Wrong user ownership"
+    test "$(stat "$TMPDIR" --format "%g")" -eq "$(id -g)" || die "$TMPDIR: Wrong group ownership"
+    chmod 700 "$TMPDIR"
 }
 
 
@@ -56,7 +55,7 @@ create_cache_file()
     # This needs root permissions to access all files in directories.
     # If "sudo" is not configured for this user, do this step manually.
 
-    sudo qdirstat-cache-writer -l / $ROOT_CACHE
+    sudo qdirstat-cache-writer -l / "$ROOT_CACHE"
     echo "done."
 }
 
@@ -86,20 +85,20 @@ create_complete_filelist()
 
 filter_out_pkg_files_from_cache()
 {
-    zcat $ROOT_CACHE                             \
-        | cache-exclude $FILELIST                \
-        | egrep -v '^.\s+/(home|tmp|root|var)/'  \
-        | egrep -v '^.\s+/usr/lib/sysimage/rpm/' \
-        | cache-kill-empty-dirs                  \
-        | gzip                                   \
-        >$UNPKG_CACHE
+    zcat "$ROOT_CACHE"                             \
+        | cache-exclude "$FILELIST"                \
+        | grep -E -v '^.\s+/(home|tmp|root|var)/'  \
+        | grep -E -v '^.\s+/usr/lib/sysimage/rpm/' \
+        | cache-kill-empty-dirs                    \
+        | gzip                                     \
+        >"$UNPKG_CACHE"
 }
 
 
 show_filtered_cache()
 {
     echo "qdirstat -c $UNPKG_CACHE"
-    qdirstat -c $UNPKG_CACHE
+    qdirstat -c "$UNPKG_CACHE"
 }
 
 
@@ -110,13 +109,12 @@ show_filtered_cache()
 # Use -f to force re-reading all information
 
 if [ "$1"x = "-f"x ]; then
-    rm -f $ROOT_CACHE
-    rm -f $FILELIST
+    rm -f "$ROOT_CACHE"
+    rm -f "$FILELIST"
 fi
 
-test -f $ROOT_CACHE || create_cache_file
-test -f $FILELIST   || create_complete_filelist
+test -f "$ROOT_CACHE" || create_cache_file
+test -f "$FILELIST"   || create_complete_filelist
 
 filter_out_pkg_files_from_cache
 show_filtered_cache
-
