Use /tmp/qdirstat-sh and give better user feedback

diff --git a/scripts/complete-filelist-dpkg b/scripts/complete-filelist-dpkg
--- a/scripts/complete-filelist-dpkg
+++ b/scripts/complete-filelist-dpkg
@@ -6,22 +6,63 @@
 # Author:  Stefan Hundhammer <Stefan.Hundhammer@gmx.de>
 # License: GPL V2
 
-TMPDIR=/tmp
+
+SCRIPT_NAME=$(basename $0)
+
+die()
+{
+    msg="$*"
+    echo "$SCRIPT_NAME: FATAL: $msg"
+    exit 1
+}
+
+
+create_tmpdir()
+{
+    test -d $TMPDIR || mkdir -p $TMPDIR
+    test -d $TMPDIR || die "Can't create tmp dir $TMPDIR"
+}
+
+
+# Make sure the tmp directory has the right user and group ownership and
+# permissions
+
+check_tmpdir_security()
+{
+
+    test $(stat $TMPDIR --format "%u") -eq $(id -u) || die "$TMPDIR: Wrong user ownership"
+    test $(stat $TMPDIR --format "%g") -eq $(id -g) || die "$TMPDIR: Wrong group ownership"
+    chmod 700 $TMPDIR
+}
+
+
+TMPDIR=/tmp/qdirstat-$USER
+create_tmpdir
+check_tmpdir_security
+
+
 PKGLIST=$TMPDIR/pkglist.txt
 FILELIST_RAW=$TMPDIR/filelist-raw.txt
 FILELIST=$TMPDIR/filelist.txt
-REGEXP_LIST=$TMPDIR/regexp.txt
 
 
 create_pkglist()
 {
     dpkg-query --show --showformat '${Package}:${Architecture}\n' >$PKGLIST
+    wc -l $PKGLIST
+}
+
+
+clear_last_line()
+{
+    tput cuu 1 && tput el
 }
 
 
 add_filelist()
 {
     pkg=$1
+    clear_last_line
     echo "Reading file list for $pkg"
     dpkg --listfiles $pkg >>$FILELIST_RAW
 }
@@ -32,19 +73,29 @@ get_complete_filelist()
     rm -f $FILELIST_RAW
     rm -f $FILELIST
 
+    echo "Reading file lists..."
+
     for pkg in $(sort $PKGLIST); do
         add_filelist $pkg
     done
+
+    clear_last_line
 }
 
 
 filter_filelist()
 {
     echo -n "Filtering file list... "
+    
     sed -e 's/^diverted by.*to: //' <$FILELIST_RAW  | \
     grep -v '^/\.$'                                 | \
     sort -u >$FILELIST
+    
     echo " done"
+    clear_last_line
+    wc -l $FILELIST
+
+    rm $FILELIST_RAW
 }
 
 
